**Conditional Selection & Assigning data**

[https://www.kaggle.com/datasets/residentmario/ramen-ratings](https://)
[https://jakevdp.github.io/PythonDataScienceHandbook/03.03-operations-in-pandas.html
](https://)

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('ramen-ratings.csv')
df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

**Conditional Selection**

• To explore the data, ask interesting questions
1) Let's have a look at the ramen dishes served in Taiwan
2) Let's have a Bok at the ramen dishes which have ratings above tha average
3) Served dishes in Taiwan With above average ratings.
4) Get only the `Brand` and `Style` of these dishes
5) Have a look at the dishes served in both Finland and Sweden
6) Get the not null values from the `Top Ten` column

In [2]:
#1) Let's have a look at the ramen dishes served in Taiwan

Country=df['Country']

print(type(Country))
print(Country=='Taiwan')
df.loc[Country=='Taiwan'] # we used loc to get the rows with Taiwan only

<class 'pandas.core.series.Series'>
0       False
1        True
2       False
3        True
4       False
        ...
2575    False
2576    False
2577    False
2578    False
2579    False
Name: Country, Length: 2580, dtype: bool

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
40,2540,Wei Lih,GGE Noodle Snack Wheat Crackers Mexican Spicy,Pack,Taiwan,3.25,NaN
65,2515,Uni-President,Man Han Feast Spicy Beef Flavor Instant Noodles,Bowl,Taiwan,5,NaN
68,2512,Mom's Dry Noodle,Dan Dan Noodle,Pack,Taiwan,5,NaN
...,...,...,...,...,...,...,...
2500,80,Unif / Tung-I,Artificial Chicken,Pack,Taiwan,3.5,NaN
2512,68,Wei Lih,Jah Jan Mien Instant Noodle With Fried Soybean...,Pack,Taiwan,4,NaN
2522,58,Ve Wong,A-One Bun Tom Shrimp,Pack,Taiwan,3,NaN
2537,43,Kim Ve Wong,Jaopai Series: Vegetarian Instant Noodles,Bowl,Taiwan,0,NaN
2572,8,Tung-I,Chinese Beef Instant Rice Noodle,Pack,Taiwan,3,NaN

In [3]:
#2) Let's have a Bok at the ramen dishes which have ratings above tha average

# df.Stars.astype(float) # error because 'Unrated' in the data frame 

# df.Stars > 2.5 # error because Stars data type is object

df_without_unrated=df[df.Stars!='Unrated'] # the data we must remove from our data frame 
Stars=df_without_unrated.Stars.astype(float)
df_without_unrated[Stars>2.5]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
5,2575,Samyang Foods,Kimchi song Song Ramen,Pack,South Korea,4.75,NaN
6,2574,Acecook,Spice Deli Tantan Men With Cilantro,Cup,Japan,4,NaN
...,...,...,...,...,...,...,...
2564,16,Samyang,Kalgug-Su (Spicy),Pack,South Korea,3.5,NaN
2566,14,Samyang,Hot,Pack,South Korea,3.5,NaN
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5,2012 #4
2572,8,Tung-I,Chinese Beef Instant Rice Noodle,Pack,Taiwan,3,NaN
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN

In [4]:
# 3) Served dishes in Taiwan With above average ratings.

df[(df.Country == 'Taiwan') & (Stars>2.5)]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
40,2540,Wei Lih,GGE Noodle Snack Wheat Crackers Mexican Spicy,Pack,Taiwan,3.25,NaN
65,2515,Uni-President,Man Han Feast Spicy Beef Flavor Instant Noodles,Bowl,Taiwan,5,NaN
68,2512,Mom's Dry Noodle,Dan Dan Noodle,Pack,Taiwan,5,NaN
79,2501,Happy Cook,Toona Paste Noodle,Pack,Taiwan,4,NaN
...,...,...,...,...,...,...,...
2499,81,Unif / Tung-I,Artificial Spicy Beef,Pack,Taiwan,3.5,NaN
2500,80,Unif / Tung-I,Artificial Chicken,Pack,Taiwan,3.5,NaN
2512,68,Wei Lih,Jah Jan Mien Instant Noodle With Fried Soybean...,Pack,Taiwan,4,NaN
2522,58,Ve Wong,A-One Bun Tom Shrimp,Pack,Taiwan,3,NaN
2572,8,Tung-I,Chinese Beef Instant Rice Noodle,Pack,Taiwan,3,NaN

In [5]:
#4) Get only the Brand and Style of these dishes
df.loc[(df.Country == 'Taiwan') & (Stars>2.5) , [ 'Country', 'Brand' , 'Style']] #Fancy indexing

     Country             Brand Style
3     Taiwan           Wei Lih  Pack
40    Taiwan           Wei Lih  Pack
65    Taiwan     Uni-President  Bowl
68    Taiwan  Mom's Dry Noodle  Pack
79    Taiwan        Happy Cook  Pack
...      ...               ...   ...
2499  Taiwan     Unif / Tung-I  Pack
2500  Taiwan     Unif / Tung-I  Pack
2512  Taiwan           Wei Lih  Pack
2522  Taiwan           Ve Wong  Pack
2572  Taiwan            Tung-I  Pack

[191 rows x 3 columns]

In [6]:
# 5)Have a look at the dishes served in both Finland and Sweden
df[(df.Country == 'Finland') | (df.Country == 'Sweden')]
# alternative way using isin() method 
df[df.Country.isin(['Finland' , 'Sweden'])]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
675,1905,Pirkka,Nuudeli Kana Nudlar Kyckling,Pack,Finland,3.5,NaN
816,1764,Pirkka,Nuudeli Tom Yum Katkarapu,Pack,Finland,3.75,NaN
856,1724,Pirkka,Nuudeli Liha Nudlar Kott,Pack,Finland,3.5,NaN
1026,1554,ICA,Asia Fast Noodles Snabbnudlar Räksmak,Pack,Sweden,3,NaN
1063,1517,Katoz,Instant Noodles Spicy Chili,Pack,Sweden,3.5,NaN
1093,1487,ICA,Asia Snabbnudlar Kycklingsmak,Pack,Sweden,3.25,NaN

In [7]:
# 6)Get the not null values from the Top Ten column
df[~df['Top Ten'].isnull()]
df[df['Top Ten'].notnull()]

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5,2016 #10
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5,2016 #1
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5,2016 #8
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5,2016 #5
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5,2016 #9
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5,2016 #7
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5,2015 #10
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5,2015 #7
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5,2015 #4
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5,2015 #9
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5,2015 #6
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5,2015 #1
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5,2013 #10
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5,2015 #8
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5,2014 #7
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5,2014 #4
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5,2014 #9
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5,2014 #10
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5,2014 #8
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5,2014 #5
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5,2014 #6
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5,2014 #1
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5,2013 #1
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5,2013 #2
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5,2013 #4
1670,910,Paldo,Namja Ramyun,Bowl,South Korea,4.25,\n
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5,2013 #9
1846,734,Indomie,Mi Goreng Rasa Ayam Panggang Jumbo (Local),Pack,Indonesia,5,\n
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5,2013 #3
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5,2012 #10
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.5,2012 #5
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5,2012 #3
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6
2248,332,Nongshim,Champong Oriental Noodles,Cup,South Korea,3.75,\n
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.5,2012 #9
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5,2012 #1
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5,2012 #2
2535,45,Indomie,Mi Goreng Sate,Pack,Indonesia,5,\n
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4,2013 #6
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5,2012 #4

In [8]:
df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
...,...,...,...,...,...,...,...
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN

**Assigning data**

In [9]:
df['IsStyleCup'] = df.Style=='Cup'
df 
# thats a way of adding a new column to the data

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,IsStyleCup
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN,True
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN,False
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN,True
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN,False
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN,False
...,...,...,...,...,...,...,...,...
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN,False
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN,False
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN,False
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN,False
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN,False

In [10]:
#print(list(range(1 , 2580)))
#len(list(range(1 , 2580)))
#as you can see the (Review #) column starts with 2580
df['Review #']=list(range(1 , 2581))
df

,Review #,Brand,Variety,Style,Country,Stars,Top Ten,IsStyleCup
0,1,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN,True
1,2,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN,False
2,3,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN,True
3,4,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN,False
4,5,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN,False
...,...,...,...,...,...,...,...,...
2575,2576,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN,False
2576,2577,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN,False
2577,2578,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN,False
2578,2579,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN,False
2579,2580,Westbrae,Miso Ramen,Pack,USA,0.5,NaN,False